### ISSUE TITLE
Did i do something wrong?

### ISSUE THREAD

**Issue by Kurisumasuu** [KunoichiZ/SoVJP-NTR-Plugin#1]
What exectly do i need to drag in my plugin folder? or do i need something special`?  i drag´d the "00040000001A2B00" file into the folder but nothing happend. ;;

**Comment by KunoichiZ** [comment]
You need to have custom firmware. The plugin folder should be on the root of your SD card. Move the 00040000001A2B00 folder to your plugin folder. Then launch BootNTR Selector, then launch Echoes. If you see a green flash, you know the plugin worked correctly.
