### ISSUE TITLE
How do I turn off the Maximum movement cheat?

### ISSUE THREAD

**Issue by NaturalHarmonia** [KunoichiZ/SoVJP-NTR-Plugin#2]
I tried Start + Y with Cheats Enabled and with the cheat on but it didn't work. I also disabled cheats as well. I saved so I'm afraid that this might be permanent.

**Comment by KunoichiZ** [comment]
I think it's permanent. Back up your saves first before trying the cheats.

**Comment by NaturalHarmonia** [comment]
It's permanent along with the all stats up by level up cheat.

**Comment by KunoichiZ** [comment]
The all stats by level up cheat isn't permanent though. I've saved after using it and played without cheats and I didn't get all stats by level up. It's most definitely not permanent. I just tested it.
