### ISSUE TITLE
100 Exp Cheat is not working

### ISSUE THREAD

**Issue by ColeExalted** [KunoichiZ/SoVJP-NTR-Plugin#3]
100 exp cheat is not working. Everything else is working fine. Do I need to exactly during battle or sth?

**Comment by NaturalHarmonia** [comment]
Make sure you use Start + Up on the control pad to turn it on.

**Comment by ColeExalted** [comment]
NaturalHarmonia Thanks! Everything is working now! Finally can go on to Archanea :P
