### ISSUE TITLE
Addtional codes for getting items easily ( except DLC items )

### ISSUE THREAD

**Issue by CarterLi** [KunoichiZ/SoVJP-NTR-Plugin#5]
https://gbatemp.net/threads/gateway-cheats.402900/page-130#post-7383572

I've tested myself with NTR Plugin Manager. The code itself works, but I can't add descriptions ( converting fails constantly, have no ideas what's going wrong )

---
Old text:  
> Any cheats for getting the three endgame weapons easier?
>
> Say Sol, Luna, and Astra

**Comment by KunoichiZ** [comment]
I haven't had time to update the plugin yet. Maybe sometime next week. I know this is a late response.

**Comment by CarterLi** [comment]
The code doesn't work for v1.1. It's the time to get updated.  
Looking forward to it.

**Comment by KunoichiZ** [comment]
And the updated cheats for the US/EU versions of the game have been released, and again, I say the release will be next week.
